### Auth
GET http://localhost:3000/api/v1/auth/login
API: 123

### username es el email, asi lo define la estrategia
###
POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
  "email": "michisuper@gmail.com",
  "password": "123 michi"
}