### Getting all characters
GET http://localhost:3000/api/v1/characters

### Getting character by name 
GET http://localhost:3000/api/v1/characters?name=lalo

### Getting characters by age
GET http://localhost:3000/api/v1/characters?age=22

### Getting characters by weight
GET http://localhost:3000/api/v1/characters?weight=23.2

### Getting characters by movies id
GET http://localhost:3000/api/v1/characters?movies=6


### Getting a character by id
GET http://localhost:3000/api/v1/characters/5


### Creating a character
POST http://localhost:3000/api/v1/characters
content-type: application/json

{   
   "image": "http://placeimg.com/640/300",
   "name": "simon",
   "age": 60,
   "weight": 224,
   "history": "otra vez simon ...."
   
}

### Updating a character by id
PUT http://localhost:3000/api/v1/characters/1
content-type: application/json

{   
   "image": "http://placeimg.com/640/300",
   "name": "queen",
   "age": 22,
   "weight": 212.2,
   "history": "otra vez ...."
   
}

### Deleting a character by id
DELETE  http://localhost:3000/api/v1/characters/2


