### Getting all characters
GET http://localhost:3000/api/v1/characters

### Getting character by name 
GET http://localhost:3000/api/v1/characters?name=pepe

### Getting characters by age
GET http://localhost:3000/api/v1/characters?age=20

### Getting characters by weight
GET http://localhost:3000/api/v1/characters?weight=76

### Getting characters by movies id
GET http://localhost:3000/api/v1/characters?movies=5


### Getting a character by id
GET http://localhost:3000/api/v1/characters/3


### Creating a character
POST http://localhost:3000/api/v1/characters
content-type: application/json

{   
   "image": "http://placeimg.com/640/300",
   "name": "joako",
   "age": 33,
   "weight": 90,
   "history": "otra vez kasooss ...."
   
}

### Updating a character by id
PUT http://localhost:3000/api/v1/characters/3
content-type: application/json

{   
   "image": "http://placeimg.com/640/300",
   "name": "lore",
   "age": 15,
   "weight": 89,
   "history": "otra vez lore...."
   
}

### Deleting a character by id
DELETE http://localhost:3000/api/v1/characters/2


