### Getting all genders
GET http://localhost:3000/api/v1/genders


### Creating a gender
POST http://localhost:3000/api/v1/genders
content-type: application/json

{   
   "name": "terror",
   "image": "http://placeimg.com/640/400"
}

### Associate a movie with a gender 
POST http://localhost:3000/api/v1/genders/add-movie
content-type: application/json

{   
   "movieId": 2,
   "genderId": 1
}


### Updating a gender by id
PUT http://localhost:3000/api/v1/genders/1
content-type: application/json

{   
   "name": "comedy",
   "image": "http://placeimg.com/640/400"
}
### Deleting a gender by id
DELETE  http://localhost:3000/api/v1/genders/2


