### Getting all movies
GET http://localhost:3000/api/v1/movies

### Getting a movie by id
GET http://localhost:3000/api/v1/movies/2

### Getting a movie by name
GET http://localhost:3000/api/v1/movies?name=criptomania

### Getting a movie by gender id
GET http://localhost:3000/api/v1/movies?genre=1

### Getting movies by order ASC | DESC
GET http://localhost:3000/api/v1/movies?order=ascsd

### Creating a movie
POST http://localhost:3000/api/v1/movies
content-type: application/json

{   
   "image": "http://placeimg.com/640/400",
   "title": "anabel",
   "score": 5
}

### Associate a movie with a character 
POST http://localhost:3000/api/v1/movies/add-character
content-type: application/json

{   
   "movieId": 2,
   "characterId": 4
}

### Updating a movie by id
PUT http://localhost:3000/api/v1/movies/2
content-type: application/json

{   
   "image": "http://placeimg.com/640/300",
   "title": "king of kings",
   "score": 5   
}

### Deleting a movie by id
DELETE  http://localhost:3000/api/v1/movies/1